name: Build Wheels

on : [push, pull_request]

jobs:

  build_package:
    name: Build ${{ github.event.repository.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
            path_ccache: ~/.cache/ccache
          - os: macos-latest
            path: ~/Library/Caches/pip
            path_ccache: ~/Library/Caches/ccache
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
            path_ccache: ~\AppData\Local\ccache\Cache

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Activating Python cache
        uses: actions/cache@v2
        id: cache_python
        continue-on-error: true
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install ccache for Linux and Mac
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt -y install ccache
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install --HEAD ccache
          fi
        shell: bash

      - name: ccache cache files
        uses: actions/cache@v2
        id: cache_ccache
        continue-on-error: true
        with:
          path: ${{ matrix.path_ccache }}
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Install dependencies
        run: |
          # The --upgrade and --upgrade-strategy eager flags ensure that pip will always install the latest allowed version of all the dependencies.
          python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Build giotto-ph
        run: |
          python -m pip install -e .
        env:
          CC: "ccache gcc"
          CXX: "ccache g++"
          CCACHE_DIR: ${{ matrix.path_ccache }}
          CCACHE_COMPRESS: 1
          CCACHE_MAXSIZE: 4G

      - name: Run test
        run: |
          python -m pip install pytest 
          python -m pytest

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: build_package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Specify which Python versions to build wheels
          # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
          # Skip 32 bit architectures
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          CIBW_BEFORE_BUILD: python -m pip install cmake
          CIBW_TEST_COMMAND: python -m pytest {package}/giotto_ph/test
          CIBW_TEST_REQUIRES: pytest

      - uses: actions/upload-artifact@v2
        name: Upload wheels
        with:
          path: ./wheelhouse/*.whl
